replicaCount: 5

image:
  repository: 917318837741.dkr.ecr.ap-south-1.amazonaws.com/sample-app
  tag: "1.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  className: alb
  scheme: internet-facing
  targetType: ip
